baseURL = "https://ambitious-river-054aa4203.azurestaticapps.net/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Azure Family - Azure User Groups around the world"
theme = "cupper"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "docs"

[params]
  editURL = "https://github.com/weeyin83/azureusergroup"
  description = "Azure Family - Azure User Groups around the world"
  author = "Sarah Lean"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "mine"
  disableLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Azure Family - Azure User Groups around the world"
weight = 1
languageName = "English"

