baseURL:  https://ambitious-river-054aa4203.azurestaticapps.net/
languageCode: en-us
defaultContentLanguage: en
title: Azure Family - Azure User Groups around the world
theme: cupper
googleAnalytics: UA-123456789-1
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Find your friendly local Azure user group!
  homeMetaContent: Find your friendly local Azure user group!
  footer: Built with <i class="fas fa-heart"></i> by [Sarah Lean](https://www.techielass.com), hosted on [Azure](link).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: SarahLean
  katex: true
  darkThemeAsDefault: false
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css
  accent: "blue"
  showBorder:  true
  editURL: "https://github.com/weeyin83/AzureFamily/tree/master/docs/"
  author: "Sarah Lean"
  showVisitedLinks: false
  disableBreadcrumb: false
  disableNextPrev: true
  themeVariant: "mine"
  disableLanguageSwitchingButton: true
  github: "weeyin83" 
  twitter: "Techielass" # add your twitter profile
  email: "myemail@myaddress.xxx"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Africa User Groups
      url: /Africa/
      weight: 2
    - name: Asia User Group
      url: /Asia/
      weight: 3
    - name: Canada User Groups
      url: /Canada/
      weight: 4
    - name: Europe User Groups
      url: /Europe/
      weight: 5
    - name: Germany User Groups
      url: /Germany/
      weight: 6
    - name: Oceania User Groups
      url: /Oceania/
      weight: 7
    - name: Rest of the World User Groups
      url: /ROTW/
      weight: 8
    - name: US User Groups
      url: /US/
      weight: 9
    - name: UK User Groups
      url: /UK/
      weight: 10
    - name: About
      url: /about/
      weight: 11
    - name: RSS
      url: /index.xml
      weight: 12

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
